### ISSUE TITLE
can't install supabase-todolist (powersync_attachments_helper +3)

### ISSUE THREAD

**Issue by JavascriptMick** [powersync-ja/powersync.dart#159]
in the demo src code, pubspec.yml references build +3 
```
dependencies:
  flutter:
    sdk: flutter
  powersync_attachments_helper: ^0.6.5+3
```
but this is not deployed to pub.dev (presumably yet) causing the following resolution failure

```
>... supabase-todolist % flutter pub get     
Resolving dependencies... 
Because powersync_flutter_demo depends on powersync_attachments_helper ^0.6.5+3 which doesn't match any versions, version solving failed.
```
