### ISSUE TITLE
sync_rules not working as intended

### ISSUE THREAD

**Issue by JCKodel** [powersync-ja/powersync.dart#187]
I have these tables:

```
users (id = userId)

user_devices (user_id and device_id)

devices (id = device_id)
```

My sync_rules.yaml is:

```yaml
bucket_definitions:
  #global:
    #data:
      #- SELECT * FROM lists
      #- SELECT * FROM todos
  user_data:
    parameters: 
      - SELECT token_parameters.user_id as user_id
    data:
      - SELECT * FROM users WHERE id = bucket.user_id
      - SELECT * FROM user_settings WHERE user_id = bucket.user_id
      - SELECT * FROM user_logins WHERE user_id = bucket.user_id
      - SELECT * FROM user_devices WHERE user_id = bucket.user_id
  device_data:
    parameters:
      - SELECT device_id FROM user_devices WHERE user_id = token_parameters.user_id
    data:
      - SELECT * FROM devices WHERE device_id = bucket.device_id
```

So, basically, I'm returning everything I can know which user has ownership, then, on the table `devices`, I select a `device_id` from a table where I can determine ownership, then return all devices that exists on that query.

At run time, the row is inserted in SQLite, then sync for Postgres, but, next time the app runs, `devices` table is empty!
