### ISSUE TITLE
Sync Rules Not Filtering Data Based on client params

### ISSUE THREAD

**Issue by tejas-codiste** [powersync-ja/powersync.dart#234]
I am trying to sync only the relevant data based on a `user_id` parameter. However, instead of fetching only the filtered data, the entire database is being synced to the local device.

**Expected Behavior**

Only the data matching the user_id parameter should be synced to the local database.

**Actual Behavior**

The entire database is synced, ignoring the filtering rules logic in the sync rules.

PowerSync Sync Rules Configuration

I have defined the following sync rule in the PowerSync console:

```
bucket_definitions:
  by_user_parameter:
    parameters: SELECT (request.parameters() ->> 'user_id') as user_id
    data:
      - SELECT * FROM creators WHERE creators.user_id = bucket.user_id
      - SELECT * FROM events WHERE events.creator_user = bucket.user_id
      - SELECT attendee.* FROM attendee 
        JOIN events ON attendee.event_id = events.event_id 
        JOIN creators ON events.creator_user = creators.user_id 
        WHERE creators.user_id = bucket.user_id
      - SELECT * FROM pin WHERE pin.user_id = bucket.user_id
      - SELECT device.* FROM device 
        JOIN pin ON device.pin_id = pin.uid 
        JOIN creators ON pin.user_id = creators.user_id 
        WHERE creators.user_id = bucket.user_id
      - SELECT * FROM check_in_logs WHERE user_id = bucket.user_id
```

Flutter Code for Connecting to PowerSync

```
currentConnector = SupabaseConnector(db);
db.connect(
    connector: currentConnector!,
    params: {'user_id': user.userId});
```

This issue prevents implementing user-specific data syncing, which is a core requirement for my application. Any guidance on resolving this would be appreciated.

**Comment by Chriztiaan** [comment]
Hey @tejas-codiste, firstly just a note on client parameters. They aren't specifically secure as a client could specify any `user_id`, for `user_id` specifically we would generally recommend to pull the `user_id` from the JWT token. An example of this could be found here: https://docs.powersync.com/usage/sync-rules/organize-data-into-buckets

Ignoring the `user_id` label, your sync rules should still have worked though as it looks correct when look at: https://docs.powersync.com/usage/sync-rules/advanced-topics/client-parameters

**Comment by tejas-codiste** [comment]
Thanks for your kind reply. I went through the shared link, but my question remains the same. I want to load only the data related to user_id, not the entire database. I'm not using Supabase Auth in the app. Could you lease let me know how to achieve this?.

**Comment by Chriztiaan** [comment]
Okay so first part would be ensuring that specify the `user_id` in your auth token. Where your token is exposed in the `fetchCredentials` function of your connector. What backend/database pair are you currently using? Is this a fresh project or are you potentially moving from Atlas Sync @tejas-codiste ?


Then you would have something like this (note joins aren't supported in the sync rules yet).

```
bucket_definitions:
  by_user_parameter:
    parameters: SELECT request.user_id() as user_id
    data:
      - SELECT * FROM creators WHERE creators.user_id = bucket.user_id
      - SELECT * FROM events WHERE events.creator_user = bucket.user_id
      ....
```

**Comment by tejas-codiste** [comment]
Thanks, @Chriztiaan!

I'm still facing an issue where the entire PowerSync database is being backed up locally on the device. Could you please review my refactored bucket definitions and the Flutter-side code where I'm passing the user_id to get a better understanding of the issue?

Bucket Definitions:

```
bucket_definitions:
  by_user_parameter:
    # request.user_id() is the same as the previous token_parameter.user_id
    parameters: SELECT request.user_id() as user_id
    data:
      - SELECT * FROM creators WHERE creators.user_id = bucket.user_id
      - SELECT * FROM events WHERE events.creator_user = bucket.user_id
      - SELECT * FROM attendee WHERE event_id IN (SELECT event_id FROM events WHERE creator_user = bucket.user_id)
      - SELECT * FROM pin WHERE pin.user_id = bucket.user_id
      - SELECT * FROM device WHERE pin_id IN (SELECT uid FROM pin WHERE user_id = bucket.user_id)
      - SELECT * FROM check_in_logs WHERE user_id = bucket.user_id 
```

Flutter Code (Passing user_id):

Additionally, I’m unable to see the newly created bucket in the [Diagnostics Console](https://diagnostics-app.powersync.com/sql-console) (screenshot attached). It only shows the global bucket, even though I’ve commented out the global bucket and redeployed the rules.

```

<img width="1434" alt="Image" src="https://github.com/user-attachments/assets/faad7375-e4f0-423f-8036-3c51f466ccd7" />

```

Could you help me ensure that only user-specific data is backed up based on user_id?
Thanks in advance!
